supabase:
  storage:
    endpoint: https://wocnbawniekaxvgtfxno.storage.supabase.co/storage/v1/s3
    bucket: test
    region: ap-northeast-1
    accessKey: 00a05fcb0f8ebbd13cc5a59bb32072ae
    secretKey: 5f3e44668ade0ecc86e921e8d8c95f970b6ce0f8019915a5e819a00ea21957f4